# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink: /:title/

# Setup
title:            Science Chops
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme ...'
url:              "https://spi.blue"   # Your main domain here
baseurl:          "/blog"              # This is the subdirectory where your site lives

author:
  name:           'spiritual blues'
  url:            "https://spi.blue"

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
